use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :lolcommit_server, LolcommitServerWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :lolcommit_server, LolcommitServerWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/lolcommit_server_web/{live,views}/.*(ex)$",
      ~r"lib/lolcommit_server_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :arc,
  bucket: "rzr911",
  virtual_host: true

config :ex_aws,
  access_key_id: "AKIAIO7V2FZCGJWK2HXA", 
  secret_access_key: "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",
  region: "ap-south-1",
 host: "s3.ap-south-1.amazonaws.com",
 s3: [
 scheme: "https://",
 host: "s3.ap-south-1.amazonaws.com",
 region: "ap-south-1"
 ]

# Configure your database
config :lolcommit_server, LolcommitServer.Repo,
  username: "tushar",
  password: "iygn67u9",
  database: "lolcommit_server_dev",
  hostname: "localhost",
  pool_size: 10
